[pytest]
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:jose.*
    ignore::DeprecationWarning:passlib.*
    ignore::DeprecationWarning:paddleocr.*
    ignore::DeprecationWarning:paddle.*
    ignore::UserWarning:paddle.*
    ignore::ResourceWarning
    ignore::pytest.PytestUnraisableExceptionWarning
